### PR TITLE
Add license metadata to python package declaration

### PR DESCRIPTION
**Pull request by pbardondev**
I am trying to import this package into an internal repository using an internal procurement process and it is failing to find the license, I would like to add this additional license metadata to the python package to see if that will help.

Also, I did not find release instructions, could you help me process this change for release to the PyPI repository?

Thanks!

### CODE REVIEW

**Review by scriptsrc — APPROVED** [review]

**Comment by scriptsrc** [comment]
Hey @pbardondev - Thanks for this. I've never used license metadata before. Thanks for contributing. Merging now.

**Comment by pbardondev** [comment]
@scriptsrc no problem, will this get automatically released or is there something else I need to do?

**Comment by scriptsrc** [comment]
image

**Comment by scriptsrc** [comment]
(Kidding - another action uploads to pypi. Hopefully tomorrow. I'll update this thread when that's done)

**Comment by pbardondev** [comment]
Awesome, thanks! Let me know if you need me to change anything on my end...

**Comment by scriptsrc** [comment]
Looks like it's available in `policyuniverse 1.3.2.20210107`

https://pypi.org/project/policyuniverse/

@pbardondev

**Pull request merged**
