### PR TITLE
Optimize action expansion logic

### PR DESCRIPTION
**Pull request by patricksanders**
This PR optimizes a hot path in the action wildcard expansion flow. The `_expand_wildcard_action()` function now maps a new `_expand()` function over the list of actions. For the `_expand()` function, I opted to use `fnmatch.filter()` instead of `fnmatch.fnmatchcase()` for a pretty significant performance improvement.

The `_expand_wildcard_action()` has a _really_ ugly list comprehension to flatten a list of lists. It's basically impossible to read, but there's another significant performance improvement with this change. StackOverflow reference for the ugly part: https://stackoverflow.com/a/952952

With some quick profiling, the changes in this PR decreased the time Repokid spent in this codepath from 30 seconds to 10 seconds for a collection of ~100 roles.

### CODE REVIEW

**Comment by scriptsrc** [comment]
That's a pretty fantastic performance improvement @patricksanders. Great job.

**Comment by patricksanders** [comment]
Uh oh, the builds are very unhappy with me.

**Comment by patricksanders** [comment]
@scriptsrc Do you want to merge #91, then I can update the version number in this PR before merging?

**Comment by scriptsrc** [comment]
@patricksanders - Okay I have merged #91.

**Review by castrapel — APPROVED** [review]

**Pull request merged**
